base_url = "https://www.dan.games"
title = "dan"
default_language = "zh"
compile_sass = true
highlight_code = true
build_search_index = false
generate_rss = true
taxonomies = [{name = "tags", rss = false}, {name = "types", rss = false}]
[extra]
copyright = "2016-2021 © Dan <a rel=\"license\" href=\"http://creativecommons.org/licenses/by-nc-nd/4.0/\">some right reserved.</a>"
